# Usamos Node.js 18
FROM node:18

# Carpeta de la app
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos todo el proyecto
COPY . .

# Exponemos el puerto
EXPOSE 3000

# Comando para correr la app
CMD ["npm", "run", "dev"]
